AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda for AI Photo Search
Resources:
  SearchPhotosLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos1
      Handler: search-photos.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos-copy
      Description: 'Lambda function for searching photos'
      Role: 'arn:aws:iam::932961230827:role/service-role/search-photos-role-e7vedwwq'
      Environment:
        Variables:
          REGION: us-east-1
  IndexPhotosLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photo1
      Handler: index-photo.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos-copy
      Description: 'Lambda function for indexing photos'
      Role: 'arn:aws:iam::932961230827:role/service-role/index-photo-role-v23r3i6e'
      Environment:
        Variables:
          REGION: us-east-1
    
