AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda for AI Photo Search
Resources:
  saerch-photos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos1
      Handler: search-photos.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos-copy
      Description: 'Lambda function for searching photos'
      Role: 'arn:aws:lambda:us-east-1:932961230827:function:search-photos'
      Environment:
        Variables:
          REGION: us-east-1
  index-photo:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photo1
      Handler: index-photo.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos-copy
      Description: 'Lambda function for indexing photos'
      Role: 'arn:aws:lambda:us-east-1:932961230827:function:index-photo'
      Environment:
        Variables:
          REGION: us-east-1
    
